// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeiCv6yTehXTN0llXr1Zkn3EJQTr98Ydg',
    appId: '1:53109806782:web:fdedfa65e91c3668f770ef',
    messagingSenderId: '53109806782',
    projectId: 'login-a08fa',
    authDomain: 'login-a08fa.firebaseapp.com',
    storageBucket: 'login-a08fa.appspot.com',
    measurementId: 'G-V5R2P4VH3R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk0uT5Q3_cZNtJBzT96kdzVpu1yk_ZXuU',
    appId: '1:53109806782:android:838fe675f1ce63a1f770ef',
    messagingSenderId: '53109806782',
    projectId: 'login-a08fa',
    storageBucket: 'login-a08fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMM0achIU8bNRH_EhMLYlNiagWVSqA2ko',
    appId: '1:53109806782:ios:0ce1a00a6e431587f770ef',
    messagingSenderId: '53109806782',
    projectId: 'login-a08fa',
    storageBucket: 'login-a08fa.appspot.com',
    iosClientId: '53109806782-2kepthhoodtekd5lmph9idpjg0n5tnjr.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginScreen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMM0achIU8bNRH_EhMLYlNiagWVSqA2ko',
    appId: '1:53109806782:ios:0ce1a00a6e431587f770ef',
    messagingSenderId: '53109806782',
    projectId: 'login-a08fa',
    storageBucket: 'login-a08fa.appspot.com',
    iosClientId: '53109806782-2kepthhoodtekd5lmph9idpjg0n5tnjr.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginScreen',
  );
}
